### ISSUE TITLE
Trusted Domains Issue

### ISSUE THREAD

**Issue by JulianKarhof** [kaisunc/vscodevimacademy#5] opened 2021-05-13 09:41 UTC
Whenever i try to open VVA, i see the following:
![Screenshot 2021-05-13 at 11 39 37](https://user-images.githubusercontent.com/16879777/118108130-e79f7c80-b3df-11eb-89a5-370293ef96b7.png)
I've tried this with a fresh installation of VSCode so theres no risk of other plugins interfering.

**Comment by kaisunc** [comment] 2021-05-13 14:34
did you activate using the command palette? 
ctrl+shift+p
vva.start -> start vscode vim academy -> enter

ill check that part of the code as well.

**Comment by kaisunc** [comment] 2021-05-13 14:35
i think an update broke something. fix coming up.

**Comment by kaisunc** [comment] 2021-05-13 14:42
i can't reproduce the bug though, got it once. re-installed the extension, and it seems to be working again. can you try uninstalling and re-installing the extension? thanks.

**Comment by JulianKarhof** [comment] 2021-05-13 14:58
This did fix it with my VSCode insiders install, but on my stable VSCode installation this keeps happening sadly

**Comment by kaisunc** [comment] 2021-05-13 15:06
can you tell me which version of vscode you're using? thanks

**Comment by JulianKarhof** [comment] 2021-05-13 15:19
```
Version: 1.56.1
Commit: e713fe9b05fc24facbec8f34fb1017133858842b
Date: 2021-05-06T10:08:24.325Z (1 wk ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0
```

**Comment by kaisunc** [comment] 2021-05-24 07:34
can't reproduce the bug, so closing for now

**Closed as completed by kaisunc** 2021-05-24 07:34 UTC

**Comment by mvcaaa** [comment] 2022-10-26 19:31
Same here

v1.1.9

vs code version 1.72.2

Trusted Domains it is

**Comment by kaisunc** [comment] 2022-10-27 02:28
i think this is due to a hyperlink to paypal button in the readme? i am not
entirely sure how vscode checks for domain trust.
i can't reproduce the problem though, or i might have trust all in my
settings.

**Comment by blwinters** [comment] 2023-04-29 02:26
Yeah, I had to add `*.paypal.com` to the list of Trusted Domains, then restart VS Code, then it started working.

**Comment by gorban** [comment] 2026-03-01 15:32
Still happening. Reproduction steps:

1. OS: Bazzite - KDE
   - E.g. for Nvidia hardware: <https://download.bazzite.gg/bazzite-nvidia-open-stable-live-amd64.iso>
   - You don't even have to install to disk.
2. `sudo yum install code`
   - You may need to install the key and yum repository first following the Visual Studio Code installation official docs:\
     <https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions>
3. Install VSCode Vim Academy in VS Code command palette: `ext install kaisun.vscodevimacademy`
   - **Note:** I installed vscodevim extension afterwards, and via the View - Extensions, different than how I installed vscodevimacademy
4. Open VSCode Vim Academy in VS Code command palette: `Start VScode Vim Academy`

But, opening a new VSCode window afterwards, it launches fine 🤷‍♂️
